import {Product} from './product.model';
export const PRODUCTS: Product[] = [
    {
      productId: 1,
      productName: 'Aviary',
      suitColors: 'red, black',
      faceType: 'standard',
      theme: 'birds',
      backgroundColor: 'white',
      price: 5.99,
      description:
        'Bird lovers from all over flock together to find a copy of this lovely deck',
      pic: '',
      quantity: 17,
    },
    {
      productId: 2,
      productName: 'Fyrebird',
      suitColors: 'red, black',
      faceType: 'fancy',
      theme: 'birds, myth',
      backgroundColor: 'white',
      price: 6.99,
      description:
        'This deck is a real hot commodity with phoenixes gracing the back and the suit symbols set ablaze',
      pic: '',
      quantity: 450,
    },
    {
      productId: 3,
      productName: 'Dark Mode',
      suitColors: 'blue, green',
      faceType: 'standard',
      theme: 'tech',
      backgroundColor: 'black',
      price: 6.99,
      description:
        'Do white background cards burn your eyes? If so then do we have a deck for you!',
      pic: '',
      quantity: 56,
    },
    {
      productId: 4,
      productName: 'Dragon',
      suitColors: 'red, black',
      faceType: 'fancy',
      theme: 'myth',
      backgroundColor: 'white',
      price: 5.99,
      description:
        'Mythical beasts of majesty dawn the backs of these gorgeous cards',
      pic: '',
      quantity: 77,
    },
    {
      productId: 5,
      productName: 'Riderback - red',
      suitColors: 'red, black',
      faceType: 'standard',
      theme: 'cards',
      backgroundColor: 'white',
      price: 4.99,
      description: 'An all-time classic',
      pic: '',
      quantity: 100,
    },
    {
      productId: 6,
      productName: 'Riderback - blue',
      suitColors: 'red, black',
      faceType: 'standard',
      theme: 'cards',
      backgroundColor: 'white',
      price: 4.99,
      description: 'An all-time classic',
      pic: '',
      quantity: 100,
    },
    {
      productId: 7,
      productName: 'Stargazer',
      suitColors: 'same',
      faceType: 'standard',
      theme: 'space',
      backgroundColor: 'black',
      price: 5.99,
      description:
        'Lovers of the stars unite! These cards will let you see far into the reaches of outer space any time of day',
      pic: '',
      quantity: 33,
    },
    {
      productId: 8,
      productName: 'Stargazer: Sunspot',
      suitColors: 'same',
      faceType: 'standard',
      theme: 'space',
      backgroundColor: 'maroon',
      price: 5.99,
      description:
        'Unlike the actual sun, you can stare at these beauties all day and still retain your sight',
      pic: '',
      quantity: 27,
    },
    {
      productId: 9,
      productName: 'Avengers',
      suitColors: 'red, black',
      faceType: 'fancy',
      theme: 'tv/movies',
      backgroundColor: 'white',
      price: 7.99,
      description: 'Every marvel fans favorite deck',
      pic: '',
      quantity: 15,
    },
  ];
  